### ISSUE TITLE
Response Code 500 versus Standard 429

### ISSUE THREAD

**Issue by sloanb** [lob/hapi-rate-limiter#28]
While implementing this plugin I found that returning the response code of 500 is not fitting for the API based rate-limiting in general. Typically you would want the response code to be a 429 Too Many Request. 

Would you consider allowing for adjustments based on configuration for the status code. The example below allows for defining the status code within plugin settings however defaults to 429 or which ever you prefer. 

**Example response adjustment:**
```
      if (remaining < 0) {
        debugger;
        return reply.response(options.overLimitError(rate)).code(options.errorStatusCode ? options.errorStatusCode : 429);
      }
```
Thanks for providing this module. Look forward to hearing your response.

**Comment by typedefstructer** [comment]
just in case anyone else is facing this issue,
I solved it with 
`overLimitError: (_rate) => Boom.tooManyRequests('you have exceeded your request limit')`
